### PR TITLE
Removed built in editor, use notepad, wordpad or word

### PR DESCRIPTION
**Pull request by sabrogden**

### CODE REVIEW

**Comment by joshdcurry** [comment]
@sabrogden Is it still possible to use the built in editor instead of opening in an external program? How?

**Comment by mid787** [comment]
@sabrogden 
IMHO this is bad. now when the editor is opened /  exit , you lose the ditto window ( effectivly closed)
on the prev versions the editor wouldve been closed and you still saw the ditto window.

going back until it's going to be fixed

**Comment by sabrogden** [comment]
What version are going back to?  I went back to try on version 3.23.124 and when opening the editor Ditto close the clip list.

**Comment by mid787** [comment]
You r right. I dont knownwhybi thought so.

Anyway is it possible not to close the ditto once edit is opened?

**Comment by walktheweb** [comment]
We lost more functionality. Closing the old editor with Shift+Esc will put the content on your clipboard.
Now I need to select it, copy it, then close Notepad and as @RoyiNamir mentioned we lost the focus on Ditto.
It would be nice to choose between the old (with the special exit functionality) and a different editor.

**Comment by mid787** [comment]
@sabrogden  , @walktheweb  - Related : https://github.com/sabrogden/Ditto/issues/939

**Pull request merged**
